name: CI - CD

on:
    push:
        branches: [main]
    pull_request:
        branches:
            - '**'

jobs:
    first_interaction:
        if: github.event_name == 'pull_request'
        name: 'first interaction'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/first-interaction@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  pr-message: |
                      Thanks for your first pull request on this project!
                      This is a kindly reminder to read the following resources:
                      - [code of conduct]()
                      - [contribution guidelines]()
                      It'll help us to review your contribution and to ensure it's aligned with our standards.
    greetings:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - uses: kerhub/saved-replies@v1.0.0
              with:
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  reply: |
                      Hi @${{ github.event.pull_request.user.login }}, thanks for being part of the community :heart:
                      We'll review your contribution as soon as possible!
    linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.4.1
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci
            - run: npx eslint
    unit_tests:
        name: 'unit tests'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.4.1
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci
            - run: npm run test
    # lighthouse_preview:
    #     name: 'lighthouse preview'
    #     uses: kerhub/reusable-workflows/.github/workflows/lighthouse-preview.yml@main
    #     with:
    #         siteName: 'kritb'
    #     secrets:
    #         netlifyAuthToken: '${{ secrets.NETLIFY_AUTH_TOKEN }}'
    # lighthouse_live:
    #     name: 'lighthouse live'
    #     uses: kerhub/reusable-workflows/.github/workflows/lighthouse-live.yml@main
    #     with:
    #         siteUrl: 'https://kritb.netlify.app/'
